create table users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null unique,
    password_hash varchar(255) not null,
    display_name varchar(120) not null,
    role varchar(20) not null,
    active boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    refresh_token_hash varchar(64) not null unique,
    device_id varchar(255),
    expires_at timestamp with time zone not null,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table stored_books (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    file_name varchar(255) not null,
    content_type varchar(120),
    file_size bigint not null,
    storage_path varchar(1024) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_stored_books_user_book unique (user_id, book_hash)
);

create table library_books (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    title varchar(255) not null,
    author varchar(255),
    publisher varchar(255),
    cover_image_url varchar(1024),
    description text,
    total_pages integer,
    last_opened_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_library_books_user_book unique (user_id, book_hash)
);

create table reading_progress (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    device_id varchar(255),
    locator varchar(4000),
    progress_percent double precision not null,
    completed boolean not null,
    last_read_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_reading_progress_user_book unique (user_id, book_hash)
);

create table bookmarks (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    locator varchar(1024) not null,
    chapter varchar(255),
    label varchar(255),
    note varchar(2000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table highlights (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    locator varchar(1024) not null,
    selected_text text not null,
    color varchar(32),
    note varchar(2000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table collections (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    name varchar(120) not null,
    description varchar(2000),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table collection_books (
    id bigint generated by default as identity primary key,
    collection_id bigint not null references collections(id) on delete cascade,
    book_hash varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_collection_books_collection_book unique (collection_id, book_hash)
);

create table transfer_sessions (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    session_code varchar(32) not null unique,
    source_device_id varchar(255),
    target_device_id varchar(255),
    status varchar(20) not null,
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table store_books (
    id bigint generated by default as identity primary key,
    book_hash varchar(64) not null unique,
    title varchar(255) not null,
    author varchar(255),
    description text,
    cover_image_url varchar(1024),
    download_url varchar(1024),
    price numeric(12, 2) not null,
    currency varchar(3) not null,
    published boolean not null,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_stored_books_user_updated_at on stored_books(user_id, updated_at);
create index idx_library_books_user_updated_at on library_books(user_id, updated_at);
create index idx_reading_progress_user_updated_at on reading_progress(user_id, updated_at);
create index idx_bookmarks_user_updated_at on bookmarks(user_id, updated_at);
create index idx_highlights_user_updated_at on highlights(user_id, updated_at);
create index idx_collections_user_updated_at on collections(user_id, updated_at);
create index idx_transfer_sessions_user_updated_at on transfer_sessions(user_id, updated_at);
