create table user_cloud_books (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users(id) on delete cascade,
    book_hash varchar(64) not null,
    title varchar(255) not null,
    author varchar(255),
    file_format varchar(16),
    cover_key varchar(1024),
    file_key varchar(1024),
    file_size bigint not null default 0,
    cloud_synced boolean not null default false,
    added_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uk_user_cloud_books_user_book unique (user_id, book_hash)
);

insert into user_cloud_books (
    user_id,
    book_hash,
    title,
    author,
    file_format,
    cover_key,
    file_key,
    file_size,
    cloud_synced,
    added_at,
    updated_at
)
select
    user_id,
    book_hash,
    title,
    author,
    null,
    null,
    null,
    0,
    false,
    created_at,
    updated_at
from library_books;

create index idx_user_cloud_books_user_updated_at on user_cloud_books(user_id, updated_at);
